import { initializeApp } from 'firebase/app';
import { getFirestore, doc, getDocFromServer } from 'firebase/firestore';
import firebaseConfig from '../../firebase-applet-config.json';

// Initialize Firebase using the configuration file generated by the environment
const app = initializeApp(firebaseConfig);

// Initialize Firestore with the specific database ID
const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);

// Test database connection on boot
async function testConnection() {
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
    console.log('Firebase connection tested successfully.');
  } catch (error) {
    if (error instanceof Error && error.message.includes('the client is offline')) {
      console.error('Firebase configuration error: Client is offline.');
    } else {
      console.log('Firebase connection response received:', error);
    }
  }
}
testConnection();

export { db };
